### ISSUE TITLE
[Bug] DataSetUtil Class returns inconsistent values

### ISSUE THREAD

**Issue by AndrewTwydell** [ansible-collections/ibm_zos_core#833] opened 2023-06-29 13:25 UTC
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.3

### IBM Enterprise Python

v3.10.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

v2.15.x

### z/OS version

v2.4

### Bug description

I have been importing the `ibm/ibm_zos_core/plugins/module_utils/data_set` module utility when developing the CICS collection to use the `DataSetUtils` class' functionality - specifically the gathering of dataset info in the constructor to determine if the dataset exists or not and, if yes, the `ds_org`.

Because the tests I had written for the CICS collection were failing intermittently, I did this basic tests to see what the output of that contructor was returning. 

```python
ds = DataSetUtils(self.starting_catalog.name)
self.result['1'] = ds.ds_info
        
ds = DataSetUtils(self.starting_catalog.name)
self.result['2'] = ds.ds_info
        
ds = DataSetUtils(self.starting_catalog.name)
self.result['3'] = ds.ds_info
        
ds = DataSetUtils(self.starting_catalog.name)
self.result['4'] = ds.ds_info
        
ds = DataSetUtils(self.starting_catalog.name)
self.result['5'] = ds.ds_info
```

Which returned the following:

```json
"1": {"exists": false}, "2": {"exists": false}, "3": {"exists": true}, "4": {"exists": true}, "5": {"exists": true},
```

I can't rely on this module util because there is no way of telling if the result is valid or not, and I would be concerned this inconsistency may flow up into the zos_core modules in places?

**Comment by ddimatos** [comment] 2023-07-05 06:40
@AndrewTwydell thanks for bringing this to our attention, we will try to recreate this, I skimmed the code for a while and could not see anything that would result in an error here, its an instance class and it uses LISTDS or LISTCAT and returns a RC 0 or not. If i can recreate I will be able to write out the exact reasons why a data set is false and have something to work off from. 

Our current regression is over 1100 test cases and we don't encounter any issues, but will still evaluate. 

One thing to note, the data_set.py has 2 competing classes, unfortunately we have never prioritized the work to join them but most the team stays away from `DataSetUtils` and uses `DataSet`, there is nothing wrong with `DataSetUtils` but some day It would be nice if we merged them. 

I think DataSetUtils came into place a few yrs ago when a PR was conditionally approved so long as it extracted much of the module's logic into module_utils, and that was done with a new class over extending and reusing what we had which put us where we are today. 

Thus, would you mind trying the same test using `data_set_exists` at this [line](https://github.com/ansible-collections/ibm_zos_core/blob/40bbca5ae9caa0b6597c39cf4e60e0ede90a6938/plugins/module_utils/data_set.py#L384C9-L384C24) , it goes a bit further in that if you know the volume it will check `vtoc` where as without the volume you are relying on cataloged data sets only.

**Comment by AndrewTwydell** [comment] 2023-07-05 09:07
Thanks @ddimatos for getting back to me - I have done some more investigation as to why it was happening by recreating what DataSetUtils is doing with ZOAU MVS commands. It appears the responses from calling LISTCAT for example are inconsistent. 

The majority of the outputs look like the following...

When dataset exists: (can see in stdout that it's been found with RC 0 and info about dataset)
```json
{
            "rc": 0,
            "stderr": "",
            "stdout": "1IDCAMS  SYSTEM SERVICES                                           TIME: 10:20:58        06/27/23     PAGE      1\n0        \n  LISTCAT ENTRIES('TWYDELL.CICS.IYREG01.DFHGCD')\n0CLUSTER ------- TWYDELL.CICS.IYREG01.DFHGCD\n      IN-CAT --- ICFCAT.SYSPLEX2.CATALOGB\n0   DATA ------- TWYDELL.CICS.IYREG01.DFHGCD.DATA\n      IN-CAT --- ICFCAT.SYSPLEX2.CATALOGB\n0   INDEX ------ TWYDELL.CICS.IYREG01.DFHGCD.INDEX\n      IN-CAT --- ICFCAT.SYSPLEX2.CATALOGB\n1IDCAMS  SYSTEM SERVICES                                           TIME: 10:20:58        06/27/23     PAGE      2\n0         THE NUMBER OF ENTRIES PROCESSED WAS:\n                    AIX -------------------0\n                    ALIAS -----------------0\n                    CLUSTER ---------------1\n                    DATA ------------------1\n                    GDG -------------------0\n                    INDEX -----------------1\n                    NONVSAM ---------------0\n                    PAGESPACE -------------0\n                    PATH ------------------0\n                    SPACE -----------------0\n                    USERCATALOG -----------0\n                    TAPELIBRARY -----------0\n                    TAPEVOLUME ------------0\n                    TOTAL -----------------3\n0         THE NUMBER OF PROTECTED ENTRIES SUPPRESSED WAS 0\n0IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 0\n0        \n0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 0\n"
        }
```

When the dataset does NOT exist: (Can see it's not been found in stdout)
```json
{
            "rc": 4,
            "stderr": "",
            "stdout": "1IDCAMS  SYSTEM SERVICES                                           TIME: 10:20:59        06/27/23     PAGE      1\n0        \n  LISTCAT ENTRIES('TWYDELL.CICS.REG2C2.DFHGCD')\n0IDC3012I ENTRY TWYDELL.CICS.REG2C2.DFHGCD NOT FOUND\n IDC3009I ** VSAM CATALOG RETURN CODE IS 8 - REASON CODE IS IGG0CLEG-42\n IDC1566I ** TWYDELL.CICS.REG2C2.DFHGCD NOT LISTED\n1IDCAMS  SYSTEM SERVICES                                           TIME: 10:20:59        06/27/23     PAGE      2\n0         THE NUMBER OF ENTRIES PROCESSED WAS:\n0                   AIX -------------------0\n                    ALIAS -----------------0\n                    CLUSTER ---------------0\n                    DATA ------------------0\n                    GDG -------------------0\n                    INDEX -----------------0\n                    NONVSAM ---------------0\n                    PAGESPACE -------------0\n                    PATH ------------------0\n                    SPACE -----------------0\n                    USERCATALOG -----------0\n                    TAPELIBRARY -----------0\n                    TAPEVOLUME ------------0\n                    TOTAL -----------------0\n0         THE NUMBER OF PROTECTED ENTRIES SUPPRESSED WAS 0\n0IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 4\n0        \n0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 4\n"
        }
```

However sometimes the result looks like the following, which has RC 0 but no particular indication of what happened. This behaviour also happens when calling `LISTDS` with `IKJEFT01` where the output is empty between the first and last lines.
```json
{
            "rc": 0,
            "stderr": "",
            "stdout": "1IDCAMS  SYSTEM SERVICES                                           TIME: 10:18:58        06/27/23     PAGE      1\n0        \n0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 0\n"
        }
```

**Comment by ddimatos** [comment] 2023-07-10 20:05
Somewhat related to issue #691

**Comment by ddimatos** [comment] 2023-09-26 04:50
@AndrewTwydell - Since the issue has not had any updates per the last request on July 5th (past our 60 day rentention) , we will close the issue. You can reopen and we will triage.

**Closed by ddimatos** 2023-09-26 04:50 UTC
Labels: Bug, Closed, Waiting for response
