### ISSUE TITLE
[Documentation ] Error when using escape character in zos_operator

### ISSUE THREAD

**Issue by cdlwhui** [ansible-collections/ibm_zos_core#644] opened 2023-02-16 08:11 UTC
### Documentation issue description

The doc in link https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/modules/zos_operator.html give an example for command used in zos_operator which need escape character:

```
- name: Execute an operator command to purge all job logs (requires escaping)
  zos_operator:
    cmd: "\\$PJ(*)"
```

But it reported following error when I used in following playbook:

```
    - name: spool
      zos_operator:
          cmd: "\\$DSPOOL"
```
The output is:
```
{
    "msg": "Invalid detected: Z1        2023047  02:54:51.77  S0048034   IEE305I  $DSPOOL COMMAND INVALID",
    "changed": false,
    "rc": 0,
    "content": [
        "Z1        2023047  02:54:51.77             ISF031I CONSOLE ANSIBLE ACTIVATED",
        "Z1        2023047  02:54:51.77            -\\$DSPOOL",
        "Z1        2023047  02:54:51.77  S0048034   IEE305I  $DSPOOL COMMAND INVALID",
        "",
        "",
        "Ran 0 \"\\$DSPOOL\" QUIET WAIT"
    ],
    "exception": "Invalid detected: Z1        2023047  02:54:51.77  S0048034   IEE305I  $DSPOOL COMMAND INVALID",
    "invocation": {
        "module_args": {
            "cmd": "\\$DSPOOL",
            "verbose": false,
            "wait_time_s": 0,
            "wait": true
        }
    },
    "_ansible_no_log": false
}
```

When I delete the escape character it was successful:

    - name: spool
      zos_operator:
          cmd: "$DSPOOL"

```
{
    "changed": true,
    "rc": 0,
    "content": [
        "Z1        2023047  03:09:20.12             ISF031I CONSOLE ANSIBLE ACTIVATED",
        "Z1        2023047  03:09:20.12            -$DSPOOL",
        "Z1        2023047  03:09:20.12             $HASP893 VOLUME(P2SPLL)  STATUS=ACTIVE,PERCENT=77",
        "Z1        2023047  03:09:20.12             $HASP893 VOLUME(P2SPLJ)  STATUS=ACTIVE,PERCENT=77",
        "Z1        2023047  03:09:20.12             $HASP893 VOLUME(P2SPLK)  STATUS=ACTIVE,PERCENT=11",
        "Z1        2023047  03:09:20.12             $HASP893 VOLUME(P2SPLM)  STATUS=ACTIVE,PERCENT=77",
        "Z1        2023047  03:09:20.12             $HASP893 VOLUME(P2SPLH)  STATUS=ACTIVE,PERCENT=12",
        "Z1        2023047  03:09:20.12             $HASP893 VOLUME(P2SPLI)  STATUS=ACTIVE,PERCENT=85",
        "Z1        2023047  03:09:20.12             $HASP646 25.4449 PERCENT SPOOL UTILIZATION",
        "",
        "",
        "Ran 0 \"$DSPOOL\" QUIET WAIT"
    ],
    "invocation": {
        "module_args": {
            "cmd": "$DSPOOL",
            "verbose": false,
            "wait_time_s": 0,
            "wait": true
        }
    },
    "_ansible_no_log": false
}
```

Although it finally worked for my job, I'd like to report this issue to see if it is a document issue or it is not actually working as design. 

### IBM z/OS Ansible core Version

v1.4.0-beta.1

### Ansible module

zos_operator

**Comment by ddimatos** [comment] 2023-02-24 20:04
Related to #645

**Comment by ddimatos** [comment] 2023-02-24 20:16
This is interesting in a few different ways:
- To understand the original behavior we have to go back to versions 1.3.x
- In 1.4 changes were made which I noted above that likely altered this behavior but oddly passed our regression
- In issue #645 i did recreate this with one escape `\` but did not try no escape which apparently is the correct way for 1.4.0 based on this issue.
- In 1.5.0.beta.1 we do require the escaping which i showed in issue #645 
- Our doc doc site currently caries no version, if we decided this was a doc issue and were to correct it, we could only correct it in the module doc and automation hub would show that as well. [Our doc unified doc site only shows the latest](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/modules.html) version currently 1.5.0-beta.1 doc, we have not completed the work to make that site support versions 

We will need to triage this more, thank you for opening this, its a bit of a tricky one that also still needs a bit more investigation to determine if we should correct the code (if we can given we intentionally removed the escaping).

**Comment by ddimatos** [comment] 2023-03-26 14:11
Additionally, this this enabler issue would have prevented this from happening #686

**Comment by ddimatos** [comment] 2023-03-26 14:13
@cdlwhui are you able to use IBM z/OS core versions 1.5.0-beta.1 or the coming 1.5.0 coming middle of April 2023 where this doc issue is resolved (in other words the doc issue and the command are aligned properly)?

**Comment by cdlwhui** [comment] 2023-03-27 07:48
Yes, I tried IBM z/OS core versions 1.5.0-beta.1 and it would require escape characters and will fail without the escape characters.

```
    - name: spool
      zos_operator:
          cmd: "\\$DSPOOL"
```
```
{
    "changed": true,
    "rc": 0,
    "elapsed": 0.09,
    "content": [
        "JC0        2023086  03:33:09.00             ISF031I CONSOLE ANSI0000 ACTIVATED",
        "JC0        2023086  03:33:09.00            -$DSPOOL ",
        "JC0        2023086  03:33:09.00             $HASP893 VOLUME(SPOLJ2)  STATUS=ACTIVE,PERCENT=72"
    ],
    "cmd": "\\$DSPOOL",
    "wait_time_s": 1,
    "invocation": {
        "module_args": {
            "cmd": "\\$DSPOOL",
            "verbose": false,
            "wait_time_s": 1,
            "wait": true
        }
    },
    "_ansible_no_log": false
}
```

But another confusing issue occurred about the command result where 1.4.0 could get all the command output as below but 1.5.0-beta.1 just get part of the command output after many times try.   Is there design difference for the command result fetching logic between 1.4.0 and 
1.5.0-beta.1. The 1.4.0 result below is expected which are all the command output.


```
{
    "changed": true,
    "rc": 0,
    "content": [
        "JC0       2023086  03:13:30.84             ISF031I CONSOLE ANSIBLE ACTIVATED",
        "JC0       2023086  03:13:30.84            -$DSPOOL",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJ2)  STATUS=ACTIVE,PERCENT=72",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJ5)  STATUS=ACTIVE,PERCENT=23",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJD)  STATUS=ACTIVE,PERCENT=11",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJ1)  STATUS=ACTIVE,PERCENT=11",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJ3)  STATUS=ACTIVE,PERCENT=95",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJ4)  STATUS=ACTIVE,PERCENT=11",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJB)  STATUS=ACTIVE,PERCENT=11",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJE)  STATUS=ACTIVE,PERCENT=11",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJF)  STATUS=ACTIVE,PERCENT=11",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJA)  STATUS=ACTIVE,PERCENT=11",
        "JC0       2023086  03:13:30.84             $HASP893 VOLUME(SPOLJC)  STATUS=ACTIVE,PERCENT=72",
        "JC0       2023086  03:13:30.85             $HASP646 15.0818 PERCENT SPOOL UTILIZATION",
        "",
        "",
        "Ran 0 \"$DSPOOL\" QUIET WAIT"
    ],
    "invocation": {
        "module_args": {
            "cmd": "$DSPOOL",
            "verbose": false,
            "wait_time_s": 0,
            "wait": true
        }
    },
    "_ansible_no_log": false
}
```

**Comment by cdlwhui** [comment] 2023-03-28 05:56
The zOAU version I used is 1.2.2.  I have tested using zOAU "opercmd" on z/OS and the output is also part of the command output. 

There is discussion for this issue and I have also reported in the #zoau channel. The link is:  https://ibm-systems-z.slack.com/archives/CGRPT7DRP/p1668621648962789 

What I am confused is why 1.4.0 got full output and 1.5 got part with the same zOAU version.  So it should be the change you mentioned above for 1.5 that went with a low level C implementation with ZOAU and would have the same result with zOAU.

```
>opercmd "\$dspool"
JC0        2023087  01:41:31.00             ISF031I CONSOLE HUIW0000 ACTIVATED
JC0        2023087  01:41:31.00            -$DSPOOL
JC0        2023087  01:41:31.00             $HASP893 VOLUME(SPOLJ2)  STATUS=ACTIVE,PERCENT=87
                                                                 $HASP893 VOLUME(SPOLJ5)  STATUS=ACTIVE,PERCENT=27
 >opercmd "\$dspool"
JC0        2023087  01:41:36.00             ISF031I CONSOLE HUIW0000 ACTIVATED
JC0        2023087  01:41:36.00            -$DSPOOL
JC0        2023087  01:41:36.00             $HASP893 VOLUME(SPOLJ2)  STATUS=ACTIVE,PERCENT=87
 >zoaversion
2022/12/06 20:44:00 CUT V1.2.2 ee30137 2525
```

**Comment by ddimatos** [comment] 2023-04-10 20:21
Hello @cdlwhui , regarding:

> What I am confused is why 1.4.0 got full output and 1.5 got part with the same zOAU version. 

If i understand correctly you are using ZOAU 1.2.2 with `ibm_zos_core` version 1.4.0 and questioning how you obtain full output where with `ibm_zos_core` 1.5.0 you got partial output. If that is correct and putting aside that `ibm_zos_core` 1.5.0 is not compatible or a supported with `ZOAU`. 1.5.0, let me try to explain.

Not all of the `ibm_zos_core` code uses ZOAU, in fact some of it can run without ZOAU installed, but that is not a supported option, thus depending the module and the version, the code path can vary. With `ibm_zos_core` 1.4.0 when `zos_operator` was called it ---> went to our REXX code ---> ISFEXEC ----> SDSF, thus you got the full output. 

With `ibm_zos_core` 1.5.0 the code path changes, and it looks like `ibm_zos_core` --- ZOAU ---> C , this is why the behavior is different. 


For ZOAU 1.2.2, they are aware of the partial results, they have an issue handling multiple single-line responses. This is supposed to be addressed in Q2 2023, If that is to change I will update the issue. 

When that version is released from ZOAU with the fix, there should be no development needed for `ibm_zos_core` thus we can move this issue out of stretch to validate when the fix is available. Normally we don't address changes in the same quarter, but because of the importance of this we can put it this quarters plan.

**Comment by cdlwhui** [comment] 2023-04-11 01:22
Thank you Demetri for your explanation. That make sense to me.

**Comment by ddimatos** [comment] 2023-05-30 23:48
@cdlwhui - I understand you have noted you are obtaining partial output from the module (driven by ZOAU) do you think you could open a new issue as I think this one is resolved with the doc changes. We should track your other issue in a new git issue. Thank you for your penitence and help.

**Comment by cdlwhui** [comment] 2023-05-31 15:22
Sure, I will open a new one. Thanks.

**Comment by ddimatos** [comment] 2023-05-31 18:54
@cdlwhui - actually if its ok i will create it, I checked with the ZOAU team on the second issue reported here , lets call that command truncation , and its supposed to be fixed in zoau 1.2.4 thus ill tailor an git issue around that to test and automate a test case

**Comment by ddimatos** [comment] 2023-05-31 20:23
@cdlwhui - here is the issue I created and the explanation #782

**Comment by ddimatos** [comment] 2023-05-31 20:28
The original issue with the escaping is correct with 1.5.0 or later and the docs were updated to point out that ibm_zos_core 1.5.0 requires zoau 1.2.2 or later. See doc [here](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html#id5), thus I will close this issue.

**Closed by ddimatos** 2023-05-31 20:28 UTC
Labels: Documentation, Stretch
