### ISSUE TITLE
[Bug] z/OS job submit does not seem to honor wait time and results in stack trace.

### ISSUE THREAD

**Issue by AndreMarcel99** [ansible-collections/ibm_zos_core#971] opened 2023-09-14 21:48 UTC
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.5

### IBM Enterprise Python

v3.14.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

latest

### z/OS version

None

### Bug description

To execute the correct JCL the time of execution on None fail even before just throw the error 

JCL to check
```
JCL_FILE_CONTENTS_RC_8 = """//RCBADJCL JOB MSGCLASS=A,MSGLEVEL=(1,1),NOTIFY=&SYSUID,REGION=0M
//S1 EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN DD *
 DELETE THIS.DATASET.DOES.NOT.EXIST
/*
"""
```

### Playbook verbosity output.

```
"ZOAU error":(0,"b""
{\"changed\": false, \"failed\": true, \"msg\": \"The JCL submitted with job id JOB00203 but there was an error, please review the error for further details: [ZOAUResponse]
	rc: 3
	response_format: UTF-8
	stdout_response: 
	stderr_response: BGYSC5403E Job is in phase STAT_SELECT: Awaiting selection on main and is not ready for DD queries.

	command: ddls JOB00203 ""\", \"invocation\": {\"module_args\": {\"src\": \"/tmp/tmp1vw2l37_\", \"location\": \"LOCAL\", \"max_rc\": null, \"wait_time_s\": 10, \"temp_file\": \"/tmp/ansible.p2guxm5l\", \"wait\": false, \"return_output\": true, \"use_template\": false, \"encoding\": null, \"volume\": null, \"template_parameters\": null, \"from_encoding\": \"UTF-8\", \"to_encoding\": \"IBM-1047\"}}}
","b""")
```

**Comment by richp405** [comment] 2023-09-26 15:21
I was referred to a prior zoaua issue: https://jsw.ibm.com/browse/NAZARE-9495. The current belief is the issue is resolved, since reconciling the 'blank list' issue seems to have helped.  I'll try to re-duplicate this later today to see if I can verify this.

**Comment by ddimatos** [comment] 2023-09-26 15:33
This msg below because it appears to have erred in such a way that it ignored the 10 second wait time; below zoau errors on a DD query which is done in jobs.py which has a loop around it to repeat up to `wait_time_s` , thus we should have not seen this zoau error because we would have waited 10 seconds and the produced an error that suggests we add more time to `wait_time_s` yet this error came through , thus it appears now we need to revisit the logic to see why zoau got through our code.

Error in in question:
```
ZOAU error :  (0, b'\n{"changed": false, "failed": true, "msg": "The JCL submitted with job id JOB00203 but there was an error, please review the error for further details: BGYSC5403E Job is in phase STAT_SELECT: Awaiting selection on main and is not ready for DD queries.\\n\\n\\tcommand: ddls JOB00203
```

I believe it also occurred in another reporting by Andy N where they set the wait time to 120 seconds and it came back instantly with:
![image](https://github.com/ansible-collections/ibm_zos_core/assets/25803172/f7d4cc26-ab3f-4dc6-b98e-2d3ee03454c1)

**Comment by ddimatos** [comment] 2024-03-23 14:32
@richp405 , ZOAU is embedding errors in a zoau response, as property `stderr_response`, the ansible code is not inspecting for such errors after `DDQueryException` exception, this is why the ansible code did not wait the full `wait_time_s`, the exeception should be caught and expected, Ansible enriches the experience over ZOUA and we offer additional value like wait_time_s where ZOAU would simply fail to submit. 

From the ZOAU docs:
```
    Raises
    ------
    DDQueryException
        - BGYSC3505E : If the job is not ready for DD querying yet
        - BGYSC3506E : If the job is at a transmission phase
```

You can see my 1.9.0 changes to get an idea of what we can do;
```
                try:
                    list_of_dds = jobs.list_dds(entry.id)
                except exceptions.DDQueryException as err:
                    if 'BGYSC5201E' in str(err):
                        is_dd_query_exception = True
                        pass
```

and 
```
                    try:
                        # Note, in then event of an exception, eg job has TYPRUN=HOLD
                        # list_of_dds will still be populated with valuable content
                        list_of_dds = jobs.list_dds(entry.id)
                        is_jesjcl = True if search_dictionaries("dataset", "JESJCL", list_of_dds) else False
                        is_job_error_status = True if entry.status in JOB_ERROR_STATUS else False
                    except exceptions.DDQueryException as err:
                        if 'BGYSC5201E' in str(err):
                            is_dd_query_exception = True
                            continue
```

you will notice what I am catching is specifically for TYRUN cases, error `BGYSC5201E` which is not documented by ZOAU so I will raise with ZOAU. Lets discuss this because this will need to be done after we forward port the 1.9.0 code to `dev` (1.10.0-beta.1)

**Comment by ddimatos** [comment] 2024-03-31 04:53
@richp405 - I made some code adjustments (not checked in) , to the current 1.9.0 PR merge into `dev` , i removed the specific check in the `except` , `if 'BGYSC5201E' in str(err):` to generalize and open it up to all types of `DDQueryException`'s. My local tests ran fine, I have about 20 in a playbook, I also ran this test `test_job_submit_max_rc` and was not able to reproduce, I even had commented out the `duration=0` that was in the test. 

What I suggest once the PR merges into dev, remove the two `if 'BGYSC5201E' in str(err):` , remove also the code below from `test_job_submit_max_rc` and test. If you want me to do it let me know. 

Just a note, even without these changes I was able to reproduce and I have been running regression but I do think we need to generalize the exception to catch for `DDQueryException`.

```
                 if result.get('duration'):
                     duration = result.get('duration')
                 else:
                     duration = 0
```

<img width="902" alt="image" src="https://github.com/ansible-collections/ibm_zos_core/assets/25803172/d9fd64e8-66d7-4fb0-912e-3d959384a450">

**Closed** 2024-04-22 20:33 UTC
Labels: Bug, In Plan
