### ISSUE TITLE
[Enabler] [Val] [zos_mvs_raw] Validate module with ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1140] opened 2023-12-28 05:35 UTC
## Ansible Module
`zos_mvs_raw`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

This module has no identified migration work, its test cases have minimal to no module dependencies and because it is a foundational module used by other test cases need to have regression run. This modules regression should only be run, running other regression will result in error, on success, this issue can be closed.
 
[Migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier) for reference.

**Comment by ketankelkar** [comment] 2024-01-26 21:28
The regression tests failed due to changes identified (and completed work items, pending PR review/merge:
-  #1182
- and potentially #1190

**Comment by ketankelkar** [comment] 2024-01-27 01:38
This item requires no further change. Only validation via pipeline once the PRs above are merged. Moving this to the validation column and slating it for sprint 2.

**Comment by ketankelkar** [comment] 2024-01-31 22:31
![Image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/87258a43-af73-4f9c-bc8e-2536ae919a14)



![Image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/c9d2c1c2-413f-4d45-9ae7-d0d29b4d953d)


Ran regression with the following tests:
- `./tests/unit/test_zos_mvs_raw_unit.py`
- `./tests/functional/modules/test_zos_mvs_raw_func.py`

**Closed by ketankelkar** 2024-01-31 22:31 UTC
Labels: In Plan, Enabler
