### ISSUE TITLE
[Enabler] Explore recommendations for venv & prereq init on systems with write access constraints

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#922] opened 2023-08-03 20:59 UTC
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

Ansible use with prerequisites such as ZOAU and its Python API is easy on systems that permit global write access policies. When directories are read-only, initialization becomes a bit more difficult. Options should be explored on how to best deal with this situation and educate users on the best approach.

**Requirements:**
-Explore use of Python venv's and whether they can be used for regular playbook operations
-Explore use of pip3 install --user and whether such installation paths can be readily referenced by playbook operations
-Explore use case where system has limited/no write access for prereqs. Issue recommendations and identify other solutions, if any
-Explore if z/OS Core Collection can depend on wheels only.
-Assess implications if Python API's PYTHONPATH & setuptools method were to be removed
-Document and write-up recommendations for users

**Comment by richp405** [comment] 2023-09-08 17:07
Found a potential approach:

1 - Create venv in /tmp subfolder
2 - Activate venv
3 - unpax. copy of zoau (from the super-share)
.... system (1.2.4.5) auto-detects it's in a venv and corrects the environment pathing.

I validate by setting up 1.2.5, then doing 1.2.4.5 above, and without environment change, zoaversion changed correctly.

What I didn't know before this experiment was that the virtual environment can go anywhere that's writable

Downsides: 
1 - creating the venv is a slow process
2 - it is a space-waste, since we're creating a new location set
3 - venv and tear down would be potential extra steps in the pipeline (although I'm thinking optional step, so it could be q-and-done until change.

The issue is not with zoau, but specifically with our testing pipeline, so we CAN adapt to this.

I'll leave this open until I can complete a pip install run, but I'm 99% sure there should be no impact.

**Comment by richp405** [comment] 2023-09-14 21:14
continue with this to validate wheels approachj

**Comment by storfibm** [comment] 2023-12-15 21:44
Based on the feedback, ZOAU decided to keep all current initialization methods. PYTHONPATH has changed slightly by offering a pre-compiled .so per Python version. Configure.py has been deprecated. Relevant new work items are captured in #1098 & #1099

**Comment by richp405** [comment] 2024-01-08 18:31
While we can use venv, the changes in 1.3 (keeping environment, and multiple compiled versions) mean we keep benefit without having the potential performance hits in venv/unpaxing..  I'm closing this ticket, so we can move to the new tickets in Q1 2024

**Closed by richp405** 2024-01-08 18:31 UTC
Labels: Enabler

**Comment by ddimatos** [comment] 2024-01-08 20:22
After some discussion and looking over this issue:
- It is reasonable to close this given the continued support for PYTHONPATH remains in effect for ZOAU 1.3
- I think these issues should be created to address the latest and past options available for use with Ansible:
   - (1) Evaluate, test and document the use of ZOAU wheels with Ansible, this should also include a use case as to why you might choose this over other options
   - (2) Evaluate, test and document the use of Python virtual environments, this should also include a use case as to why you might choose this over other options
   - (3) Document the use of precompiled binaries, we have this as the default in the samples but we really should put story around it and why you might choose this over other options
   - (4) Document the use of PIP zoau libs and a use case
   - (5) Probably a lengthy article on this topic might help as well. 
- Regarding  issue #1098 , I don't think that really relates to this issue other than what the team might choose to do with their infrastructure when using ZOAU 1.3, #1098 is now all about preparing the pipelines for 1.3 regression. 
- Regarding #1099, this is the epic for the entire ZOAU 1.3 migration and support, not really related to this issue.

**Comment by ddimatos** [comment] 2024-01-08 20:23
@richp405 please include your notes so that when we begin to document some of the suggestions above we can leverage your pre-existing work.
